### ISSUE TITLE
Forget to comment this line after removing permfix.sh

### ISSUE THREAD

**Issue by wiktorek140** [MOTO-M8916/old_device_motorola_msm8916-common#1]
https://github.com/MOTO-M8916/device_motorola_msm8916-common/blob/85cda6e41e67d8477c63ed75de0d317960773ed8/msm8916.mk#L120

**Comment by thopiekar** [comment]
As far as I can see fixed in the lineageos-15.1 branch. Can be closed I guess...

**Comment by wiktorek140** [comment]
But it is in lineageos-15.1-test

**Comment by thopiekar** [comment]
Oh, good catch then!
